#!/bin/bash

puppet_ver='2016.5.1'
puppet_install="puppet-enterprise-${puppet_ver}-el-7-x86_64"

curl -O https://s3.amazonaws.com/pe-builds/released/${puppet_ver}/${puppet_install}.tar.gz

tar -zxvf ${puppet_install}.tar.gz

#Populate pe.conf with root password
sed 's/.*console_admin_password.*/  "console_admin_password": "root"/' $(pwd)/${puppet_install}/conf.d/pe.conf > bootstrap-pe.conf

firewall-cmd --zone=public --add-port=3000/tcp --permanent
firewall-cmd --zone=public --add-port=443/tcp --permanent
firewall-cmd --zone=public --add-port=4433/tcp --permanent
firewall-cmd --zone=public --add-port=8140/tcp --permanent
firewall-cmd --zone=public --add-port=61613/tcp --permanent
firewall-cmd --reload


# Add a license
#cp license.key /etc/puppetlabs/license.key
#chown pe-puppet.pe-puppet /etc/puppetlabs/license.key

# copy config in place
#cp autosign.conf /etc/puppetlabs/puppet/autosign.conf

# This is equivalent to the --test/-t option but without the
# --detailed-exitcodes option
#/opt/puppetlabs/bin/puppet agent \
#  --onetime \
#  --verbose \
#  --ignorecache \
#  --no-daemonize \
#  --no-usecacheonfailure \
#  --no-splay \
#  --show_diff
